TBP/Controllers/LogsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TBP.Data;
using TBP.Services;

namespace TBP.Controllers;

public class LogsController : Controller
{
    private readonly ApplicationDbContext _context;
    private readonly IUserService _userService;

    public LogsController(ApplicationDbContext context, IUserService userService)
    {
        _context = context;
        _userService = userService;
    }
    
    public async Task<IActionResult> Index()
    {
        if (!await _userService.IsAuthenticatedAsync(HttpContext)) return RedirectToAction("Login", "Authentication");
        if (!await _userService.IsAdminAsync(HttpContext)) return Unauthorized("Only Admin can see logs");
        
        var logs = await _context.AuditLogs
            .Include(log => log.User)
            .Include(log => log.Action)
            .ToListAsync();
        
        return View("~/Views/Log/Logs.cshtml", logs);
    }
}

TBP/Controllers/UserController.cs
using System.Runtime.InteropServices.JavaScript;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using TBP.Data;
using TBP.Models;
using TBP.Services;

namespace TBP.Controllers;

public class UserController : Controller
{
    private readonly ApplicationDbContext _context;
    private readonly IUserService _userService;

    public UserController(ApplicationDbContext context, IUserService userService)
    {
        _context = context;
        _userService = userService;
    }

    public async Task<IActionResult> AllUsers()
    {
        if (!await _userService.IsAuthenticatedAsync(HttpContext)) return RedirectToAction("Login", "Authentication");
        if (!await _userService.IsAdminAsync(HttpContext)) return Unauthorized("Only Admin can see all users");
        
        return View("AllUsers", await _context.Users.OrderBy(u => u.IsDeleted).ThenBy(u => u.ID).ToListAsync());
    }

    public async Task<IActionResult> MyAccount()
    {
        if (!await _userService.IsAuthenticatedAsync(HttpContext)) return RedirectToAction("Login", "Authentication");

        int userId = int.Parse(Request.Cookies["UserId"]);
        var user = _context.Users.FirstOrDefault(u => u.ID == userId);

        return View("MyAccount", user);
    }
    
    [HttpPost]
    public async Task<IActionResult> UpdateAccount(string email, string password, string firstName, string lastName, DateTime dateOfBirth, int? userId = null)
    {
        if (!await _userService.IsAuthenticatedAsync(HttpContext)) return RedirectToAction("Login", "Authentication");
        
        if (userId == null) userId = int.Parse(Request.Cookies["UserId"]);
        var user = await _context.Users.FirstOrDefaultAsync(u => u.ID == userId);
        if (user == null)
        {
            return NotFound();
        }

        await using var connection = new NpgsqlConnection(_context.Database.GetDbConnection().ConnectionString);
        await connection.OpenAsync();

        var metadata = new Metadata {
            FirstName = firstName,
            LastName = lastName,
            DateOfBirth = dateOfBirth
        };

        var command = connection.CreateCommand();
        command.CommandText = "UPDATE users SET email = @email, password = @password, metadata = @metadata WHERE id = @userId";
        command.Parameters.AddWithValue("email", email);
        command.Parameters.AddWithValue("password", password);
        
        var metadataParameter = command.Parameters.AddWithValue("metadata", JsonSerializer.Serialize(metadata));
        metadataParameter.NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Jsonb;

        command.Parameters.AddWithValue("userId", userId);
        await command.ExecuteNonQueryAsync();

        return RedirectToAction("MyAccount");
    }

    [HttpPost]
    public async Task<IActionResult> DeleteAccount([FromRoute] int id)
    {
        if (!await _userService.IsAuthenticatedAsync(HttpContext)) return RedirectToAction("Login", "Authentication");
        if (!await _userService.IsAdminAsync(HttpContext)) return Unauthorized("Only Admin can delete a user!");
        
        var user = await _context.Users.FirstOrDefaultAsync(u => u.ID == id);
        if (user == null)
        {
            return NotFound("No user with id " + id + " found");
        }
        
        user.IsDeleted = true;
        await _context.SaveChangesAsync();
        return RedirectToAction("AllUsers");
    }
}

TBP/Views/Shared/_Layout.cshtml
@using TBP.Services
@inject IUserService UserService
@inject IHttpContextAccessor HttpContextAccessor

@{
    string userName = await UserService.GetUserNameAsync(HttpContextAccessor.HttpContext);
    bool isLoggedIn = !string.IsNullOrEmpty(userName);
    bool isAdmin = await UserService.IsAdminAsync(HttpContextAccessor.HttpContext);
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - TBP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/TBP.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TBP</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        @if (isLoggedIn)
                        {
                            <a class="nav-link text-dark">@($"Welcome {userName}")</a>
                        }
                        else
                        {
                            <a class="nav-link text-dark">Please log in</a>
                        }
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @if (!isLoggedIn)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Login">Login</a>
                        </li>   
                    }
                    @if (isAdmin)
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="adminDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Admin Actions
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="adminDropdown">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Authentication" asp-action="Register">Add New User</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="User" asp-action="AllUsers">List All Users</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Logs" asp-action="Index">Logs</a>
                                </li>
                            </ul>
                        </li>
                    }
                    @if (isLoggedIn)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="MyAccount">My Account</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Logout">Logout</a>
                        </li> 
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2025 - TBP
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>